Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [8]:
import numpy as np
N = 4
a = np.array([2,3,4]) 
def  Vandermond(a):
    print(np.column_stack([a**(N-1-i) for i in range(N)]))
Vandermond(a)

[[ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [11]:
import numpy as np
lst = []                                          # creating an empty list 
n = int(input("Enter number of elements : "))     # number of elemetns as input 
for i in range(0, n): 
    element = int(input()) 
    lst.append(element)                           # adding the element    
lst = np.array(lst)                               # converting list to array
print("Sequence array = ",lst) 

k = int(input("Enter window size "))     #window size
z = []                                   # creating an empty list
for i in range(n-k+1):
    sum = 0
    for j in range(k):
        sum = sum + lst[i+j]        
    average = sum/k
    z.append(average)                        #adding average to empty list    
z = np.array(z)
print("OUTPUT IS: ",z.T)

Enter number of elements : 13
3
5
7
2
8
10
11
65
72
81
99
100
150
Sequence array =  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Enter window size 3
OUTPUT IS:  [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
